[project]
name = "pdfs-ai-rename"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=1.102.0",
    "pypdf2>=3.0.1",
    "tiktoken>=0.11.0",
]
